### ISSUE TITLE
Fails to install because of Gridfield Bulk Editing Tools dependency

### ISSUE THREAD

**Issue by andrewandante** [silverstripe/recipe-blog#6]
Encountered when trying out the CWP 2.0.0-rc1 recipe

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for silverstripe/recipe-blog 1.0.0-rc1 -> satisfiable by silverstripe/recipe-blog[1.0.0-rc1].
    - silverstripe/recipe-blog 1.0.0-rc1 requires colymba/gridfield-bulk-editing-tools 3.x-dev -> no matching package found.
```

Worked around with:

```json

"colymba/gridfield-bulk-editing-tools": "3.0.0-beta1 as 3.x-dev"
```

in my root `composer.json` but should be pinned to something that packagist understands

**Comment by robbieaverill** [comment]
This should work now that the branches have been merged up. Still need to fix the implementation though: https://github.com/silverstripe/silverstripe-comments/issues/231
