### ISSUE TITLE
Apply the widgets and comments extensions to Blog and BlogPost rather than SiteTree

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/recipe-blog#7]
When installing the blog recipe you also get widgets and comments applied to all pages in the CMS.

These should be restricted to blog pages only by default, and let devs change the config to suit their project afterwards.

**Comment by robbieaverill** [comment]
Widgets shifted to Blog and BlogPost with #8.

In terms of the comments, the easiest path right now is probably to duplicate the config for Blog and BlogPost in the same manner.

**Comment by robbieaverill** [comment]
I've reopened this because the comments module provides default configuration to apply the CommentsExtension to SiteTree. Without changing that we still get comments functionality on every page.

**Comment by GuySartorelli** [comment]
We should just remove widgets entirely.
